version: '3.8'
services: 
  {services.postgres.name}:
    image: postgres:latest
    container_name: {services.postgres.name} 
    restart: always
    command: postgres -c config_file=/var/lib/postgresql/config/postgresql.conf
    environment:
      - POSTGRES_USER={secrets.postgres.username}
      - POSTGRES_PASSWORD={secrets.postgres.password}
    ports:
      - target: {services.postgres.internal_port}
        published: {services.postgres.external_port}
    volumes:
      # Add config
      - type: bind
        source: ./postgresql.conf
        target: /var/lib/postgresql/config/postgresql.conf
        read_only: true
      # Initialisation transactions
      - type: bind
        source: ./patches/build
        target: /docker-entrypoint-initdb.d
        read_only: true
      # Live postgres data
      - type: bind
        source: ./data
        target: /var/lib/postgresql/data
      # CSV dumps of postgres data
      - type: bind
        source: ./dumps
        target: /var/lib/postgresql/dumps