version: '3.8'
services: 
  {services.redis.name}:
    image: redis:latest
    container_name: {services.redis.name} 
    restart: always
    ports:
      - target: {services.redis.internal_port}
        published: {services.redis.external_port}
    volumes:
      # Add config
      - type: bind
        source: {folders.services}/redis/redis.conf
        target: /usr/local/etc/redis/redis.conf
        read_only: true
      # Live redis data
      - type: bind
        source: {folders.services}/redis/data
        target: /data